// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Image struct {
	ID           string          `json:"id"`
	Archive      string          `json:"archive"`
	Messier      string          `json:"messier"`
	Ngc          string          `json:"ngc"`
	Ic           string          `json:"ic"`
	Rcw          string          `json:"rcw"`
	Sh2          string          `json:"sh2"`
	Henize       string          `json:"henize"`
	Gum          string          `json:"gum"`
	Lbn          string          `json:"lbn"`
	CommonName   string          `json:"common_name"`
	Name         string          `json:"name"`
	Filename     string          `json:"filename"`
	Thumbnail    string          `json:"thumbnail"`
	Type         string          `json:"type"`
	Camera       string          `json:"camera"`
	Scope        string          `json:"scope"`
	Mount        string          `json:"mount"`
	Guiding      string          `json:"guiding"`
	Exposure     string          `json:"exposure"`
	Location     string          `json:"location"`
	Date         string          `json:"date"`
	Notes        string          `json:"notes"`
	Blink        string          `json:"blink"`
	Corrector    string          `json:"corrector"`
	Ra           sql.NullFloat64 `json:"ra"`
	Dec          sql.NullFloat64 `json:"dec"`
	Pixscale     sql.NullFloat64 `json:"pixscale"`
	Radius       sql.NullFloat64 `json:"radius"`
	WidthArcsec  sql.NullFloat64 `json:"width_arcsec"`
	HeightArcsec sql.NullFloat64 `json:"height_arcsec"`
	Fieldw       sql.NullFloat64 `json:"fieldw"`
	Fieldh       sql.NullFloat64 `json:"fieldh"`
	Orientation  sql.NullFloat64 `json:"orientation"`
	Solved       string          `json:"solved"`
}
