// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const countImages = `-- name: CountImages :one
SELECT COUNT(*) FROM images WHERE archive <> 'Y'
`

// Count queries for pagination
func (q *Queries) CountImages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countImages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countImagesByCamera = `-- name: CountImagesByCamera :one
SELECT COUNT(*) FROM images WHERE archive <> 'Y' AND camera = ?
`

func (q *Queries) CountImagesByCamera(ctx context.Context, camera string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countImagesByCamera, camera)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countImagesByScope = `-- name: CountImagesByScope :one
SELECT COUNT(*) FROM images WHERE archive <> 'Y' AND scope = ?
`

func (q *Queries) CountImagesByScope(ctx context.Context, scope string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countImagesByScope, scope)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countImagesByType = `-- name: CountImagesByType :one
SELECT COUNT(*) FROM images WHERE archive <> 'Y' AND type = ?
`

func (q *Queries) CountImagesByType(ctx context.Context, type_ string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countImagesByType, type_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countImagesNew = `-- name: CountImagesNew :one
SELECT COUNT(*) FROM images WHERE archive <> 'Y' AND date >= ?
`

func (q *Queries) CountImagesNew(ctx context.Context, date string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countImagesNew, date)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImage = `-- name: CreateImage :exec
INSERT INTO images (
    id, archive, messier, ngc, ic, rcw, sh2, henize, gum, lbn,
    common_name, name, filename, thumbnail, type, camera, scope, mount,
    guiding, exposure, location, date, notes, blink, corrector,
    ra, dec, pixscale, radius, width_arcsec, height_arcsec,
    fieldw, fieldh, orientation, solved
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?
)
`

type CreateImageParams struct {
	ID           string          `json:"id"`
	Archive      string          `json:"archive"`
	Messier      string          `json:"messier"`
	Ngc          string          `json:"ngc"`
	Ic           string          `json:"ic"`
	Rcw          string          `json:"rcw"`
	Sh2          string          `json:"sh2"`
	Henize       string          `json:"henize"`
	Gum          string          `json:"gum"`
	Lbn          string          `json:"lbn"`
	CommonName   string          `json:"common_name"`
	Name         string          `json:"name"`
	Filename     string          `json:"filename"`
	Thumbnail    string          `json:"thumbnail"`
	Type         string          `json:"type"`
	Camera       string          `json:"camera"`
	Scope        string          `json:"scope"`
	Mount        string          `json:"mount"`
	Guiding      string          `json:"guiding"`
	Exposure     string          `json:"exposure"`
	Location     string          `json:"location"`
	Date         string          `json:"date"`
	Notes        string          `json:"notes"`
	Blink        string          `json:"blink"`
	Corrector    string          `json:"corrector"`
	Ra           sql.NullFloat64 `json:"ra"`
	Dec          sql.NullFloat64 `json:"dec"`
	Pixscale     sql.NullFloat64 `json:"pixscale"`
	Radius       sql.NullFloat64 `json:"radius"`
	WidthArcsec  sql.NullFloat64 `json:"width_arcsec"`
	HeightArcsec sql.NullFloat64 `json:"height_arcsec"`
	Fieldw       sql.NullFloat64 `json:"fieldw"`
	Fieldh       sql.NullFloat64 `json:"fieldh"`
	Orientation  sql.NullFloat64 `json:"orientation"`
	Solved       string          `json:"solved"`
}

// Admin: create image
func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.ExecContext(ctx, createImage,
		arg.ID,
		arg.Archive,
		arg.Messier,
		arg.Ngc,
		arg.Ic,
		arg.Rcw,
		arg.Sh2,
		arg.Henize,
		arg.Gum,
		arg.Lbn,
		arg.CommonName,
		arg.Name,
		arg.Filename,
		arg.Thumbnail,
		arg.Type,
		arg.Camera,
		arg.Scope,
		arg.Mount,
		arg.Guiding,
		arg.Exposure,
		arg.Location,
		arg.Date,
		arg.Notes,
		arg.Blink,
		arg.Corrector,
		arg.Ra,
		arg.Dec,
		arg.Pixscale,
		arg.Radius,
		arg.WidthArcsec,
		arg.HeightArcsec,
		arg.Fieldw,
		arg.Fieldh,
		arg.Orientation,
		arg.Solved,
	)
	return err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = ?
`

// Admin: delete image
func (q *Queries) DeleteImage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteImage, id)
	return err
}

const getImage = `-- name: GetImage :one
SELECT id, archive, messier, ngc, ic, rcw, sh2, henize, gum, lbn, common_name, name, filename, thumbnail, type, camera, scope, mount, guiding, exposure, location, date, notes, blink, corrector, ra, dec, pixscale, radius, width_arcsec, height_arcsec, fieldw, fieldh, orientation, solved FROM images WHERE id = ? LIMIT 1
`

func (q *Queries) GetImage(ctx context.Context, id string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Archive,
		&i.Messier,
		&i.Ngc,
		&i.Ic,
		&i.Rcw,
		&i.Sh2,
		&i.Henize,
		&i.Gum,
		&i.Lbn,
		&i.CommonName,
		&i.Name,
		&i.Filename,
		&i.Thumbnail,
		&i.Type,
		&i.Camera,
		&i.Scope,
		&i.Mount,
		&i.Guiding,
		&i.Exposure,
		&i.Location,
		&i.Date,
		&i.Notes,
		&i.Blink,
		&i.Corrector,
		&i.Ra,
		&i.Dec,
		&i.Pixscale,
		&i.Radius,
		&i.WidthArcsec,
		&i.HeightArcsec,
		&i.Fieldw,
		&i.Fieldh,
		&i.Orientation,
		&i.Solved,
	)
	return i, err
}

const getNextByDate = `-- name: GetNextByDate :one
SELECT images.id FROM images
WHERE (images.date < (SELECT i2.date FROM images i2 WHERE i2.id = ?)
       OR (images.date = (SELECT i3.date FROM images i3 WHERE i3.id = ?) AND images.id < ?))
  AND images.archive <> 'Y'
ORDER BY images.date DESC, images.id DESC
LIMIT 1
`

type GetNextByDateParams struct {
	ID   string `json:"id"`
	ID_2 string `json:"id_2"`
	ID_3 string `json:"id_3"`
}

func (q *Queries) GetNextByDate(ctx context.Context, arg GetNextByDateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getNextByDate, arg.ID, arg.ID_2, arg.ID_3)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getNextByID = `-- name: GetNextByID :one
SELECT id FROM images
WHERE id > ? AND archive <> 'Y'
ORDER BY id ASC
LIMIT 1
`

func (q *Queries) GetNextByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getNextByID, id)
	err := row.Scan(&id)
	return id, err
}

const getNextByType = `-- name: GetNextByType :one
SELECT images.id FROM images
WHERE (images.type > (SELECT i2.type FROM images i2 WHERE i2.id = ?)
       OR (images.type = (SELECT i3.type FROM images i3 WHERE i3.id = ?) AND images.id > ?))
  AND images.archive <> 'Y'
ORDER BY images.type ASC, images.id ASC
LIMIT 1
`

type GetNextByTypeParams struct {
	ID   string `json:"id"`
	ID_2 string `json:"id_2"`
	ID_3 string `json:"id_3"`
}

func (q *Queries) GetNextByType(ctx context.Context, arg GetNextByTypeParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getNextByType, arg.ID, arg.ID_2, arg.ID_3)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getPrevByDate = `-- name: GetPrevByDate :one
SELECT images.id FROM images
WHERE (images.date > (SELECT i2.date FROM images i2 WHERE i2.id = ?)
       OR (images.date = (SELECT i3.date FROM images i3 WHERE i3.id = ?) AND images.id > ?))
  AND images.archive <> 'Y'
ORDER BY images.date ASC, images.id ASC
LIMIT 1
`

type GetPrevByDateParams struct {
	ID   string `json:"id"`
	ID_2 string `json:"id_2"`
	ID_3 string `json:"id_3"`
}

// Prev/Next for Date sort
func (q *Queries) GetPrevByDate(ctx context.Context, arg GetPrevByDateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getPrevByDate, arg.ID, arg.ID_2, arg.ID_3)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getPrevByID = `-- name: GetPrevByID :one
SELECT id FROM images
WHERE id < ? AND archive <> 'Y'
ORDER BY id DESC
LIMIT 1
`

// Prev/Next navigation (default sort by ID)
func (q *Queries) GetPrevByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPrevByID, id)
	err := row.Scan(&id)
	return id, err
}

const getPrevByType = `-- name: GetPrevByType :one
SELECT images.id FROM images
WHERE (images.type < (SELECT i2.type FROM images i2 WHERE i2.id = ?)
       OR (images.type = (SELECT i3.type FROM images i3 WHERE i3.id = ?) AND images.id < ?))
  AND images.archive <> 'Y'
ORDER BY images.type DESC, images.id DESC
LIMIT 1
`

type GetPrevByTypeParams struct {
	ID   string `json:"id"`
	ID_2 string `json:"id_2"`
	ID_3 string `json:"id_3"`
}

// Prev/Next for Type sort
func (q *Queries) GetPrevByType(ctx context.Context, arg GetPrevByTypeParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getPrevByType, arg.ID, arg.ID_2, arg.ID_3)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listAllImages = `-- name: ListAllImages :many
SELECT id, archive, messier, ngc, ic, rcw, sh2, henize, gum, lbn, common_name, name, filename, thumbnail, type, camera, scope, mount, guiding, exposure, location, date, notes, blink, corrector, ra, dec, pixscale, radius, width_arcsec, height_arcsec, fieldw, fieldh, orientation, solved FROM images ORDER BY id
`

// Admin: list all images
func (q *Queries) ListAllImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listAllImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Archive,
			&i.Messier,
			&i.Ngc,
			&i.Ic,
			&i.Rcw,
			&i.Sh2,
			&i.Henize,
			&i.Gum,
			&i.Lbn,
			&i.CommonName,
			&i.Name,
			&i.Filename,
			&i.Thumbnail,
			&i.Type,
			&i.Camera,
			&i.Scope,
			&i.Mount,
			&i.Guiding,
			&i.Exposure,
			&i.Location,
			&i.Date,
			&i.Notes,
			&i.Blink,
			&i.Corrector,
			&i.Ra,
			&i.Dec,
			&i.Pixscale,
			&i.Radius,
			&i.WidthArcsec,
			&i.HeightArcsec,
			&i.Fieldw,
			&i.Fieldh,
			&i.Orientation,
			&i.Solved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByDateDesc = `-- name: ListImagesByDateDesc :many
SELECT id, archive, messier, ngc, ic, rcw, sh2, henize, gum, lbn, common_name, name, filename, thumbnail, type, camera, scope, mount, guiding, exposure, location, date, notes, blink, corrector, ra, dec, pixscale, radius, width_arcsec, height_arcsec, fieldw, fieldh, orientation, solved FROM images
WHERE archive <> 'Y'
ORDER BY date DESC, id
LIMIT ? OFFSET ?
`

type ListImagesByDateDescParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListImagesByDateDesc(ctx context.Context, arg ListImagesByDateDescParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByDateDesc, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Archive,
			&i.Messier,
			&i.Ngc,
			&i.Ic,
			&i.Rcw,
			&i.Sh2,
			&i.Henize,
			&i.Gum,
			&i.Lbn,
			&i.CommonName,
			&i.Name,
			&i.Filename,
			&i.Thumbnail,
			&i.Type,
			&i.Camera,
			&i.Scope,
			&i.Mount,
			&i.Guiding,
			&i.Exposure,
			&i.Location,
			&i.Date,
			&i.Notes,
			&i.Blink,
			&i.Corrector,
			&i.Ra,
			&i.Dec,
			&i.Pixscale,
			&i.Radius,
			&i.WidthArcsec,
			&i.HeightArcsec,
			&i.Fieldw,
			&i.Fieldh,
			&i.Orientation,
			&i.Solved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByDateFilterCamera = `-- name: ListImagesByDateFilterCamera :many
SELECT id, archive, messier, ngc, ic, rcw, sh2, henize, gum, lbn, common_name, name, filename, thumbnail, type, camera, scope, mount, guiding, exposure, location, date, notes, blink, corrector, ra, dec, pixscale, radius, width_arcsec, height_arcsec, fieldw, fieldh, orientation, solved FROM images
WHERE archive <> 'Y' AND camera = ?
ORDER BY date DESC, id
LIMIT ? OFFSET ?
`

type ListImagesByDateFilterCameraParams struct {
	Camera string `json:"camera"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListImagesByDateFilterCamera(ctx context.Context, arg ListImagesByDateFilterCameraParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByDateFilterCamera, arg.Camera, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Archive,
			&i.Messier,
			&i.Ngc,
			&i.Ic,
			&i.Rcw,
			&i.Sh2,
			&i.Henize,
			&i.Gum,
			&i.Lbn,
			&i.CommonName,
			&i.Name,
			&i.Filename,
			&i.Thumbnail,
			&i.Type,
			&i.Camera,
			&i.Scope,
			&i.Mount,
			&i.Guiding,
			&i.Exposure,
			&i.Location,
			&i.Date,
			&i.Notes,
			&i.Blink,
			&i.Corrector,
			&i.Ra,
			&i.Dec,
			&i.Pixscale,
			&i.Radius,
			&i.WidthArcsec,
			&i.HeightArcsec,
			&i.Fieldw,
			&i.Fieldh,
			&i.Orientation,
			&i.Solved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByDateFilterNew = `-- name: ListImagesByDateFilterNew :many
SELECT id, archive, messier, ngc, ic, rcw, sh2, henize, gum, lbn, common_name, name, filename, thumbnail, type, camera, scope, mount, guiding, exposure, location, date, notes, blink, corrector, ra, dec, pixscale, radius, width_arcsec, height_arcsec, fieldw, fieldh, orientation, solved FROM images
WHERE archive <> 'Y' AND date >= ?
ORDER BY date DESC, id
LIMIT ? OFFSET ?
`

type ListImagesByDateFilterNewParams struct {
	Date   string `json:"date"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

// New images (last 12 months)
func (q *Queries) ListImagesByDateFilterNew(ctx context.Context, arg ListImagesByDateFilterNewParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByDateFilterNew, arg.Date, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Archive,
			&i.Messier,
			&i.Ngc,
			&i.Ic,
			&i.Rcw,
			&i.Sh2,
			&i.Henize,
			&i.Gum,
			&i.Lbn,
			&i.CommonName,
			&i.Name,
			&i.Filename,
			&i.Thumbnail,
			&i.Type,
			&i.Camera,
			&i.Scope,
			&i.Mount,
			&i.Guiding,
			&i.Exposure,
			&i.Location,
			&i.Date,
			&i.Notes,
			&i.Blink,
			&i.Corrector,
			&i.Ra,
			&i.Dec,
			&i.Pixscale,
			&i.Radius,
			&i.WidthArcsec,
			&i.HeightArcsec,
			&i.Fieldw,
			&i.Fieldh,
			&i.Orientation,
			&i.Solved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByDateFilterScope = `-- name: ListImagesByDateFilterScope :many
SELECT id, archive, messier, ngc, ic, rcw, sh2, henize, gum, lbn, common_name, name, filename, thumbnail, type, camera, scope, mount, guiding, exposure, location, date, notes, blink, corrector, ra, dec, pixscale, radius, width_arcsec, height_arcsec, fieldw, fieldh, orientation, solved FROM images
WHERE archive <> 'Y' AND scope = ?
ORDER BY date DESC, id
LIMIT ? OFFSET ?
`

type ListImagesByDateFilterScopeParams struct {
	Scope  string `json:"scope"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListImagesByDateFilterScope(ctx context.Context, arg ListImagesByDateFilterScopeParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByDateFilterScope, arg.Scope, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Archive,
			&i.Messier,
			&i.Ngc,
			&i.Ic,
			&i.Rcw,
			&i.Sh2,
			&i.Henize,
			&i.Gum,
			&i.Lbn,
			&i.CommonName,
			&i.Name,
			&i.Filename,
			&i.Thumbnail,
			&i.Type,
			&i.Camera,
			&i.Scope,
			&i.Mount,
			&i.Guiding,
			&i.Exposure,
			&i.Location,
			&i.Date,
			&i.Notes,
			&i.Blink,
			&i.Corrector,
			&i.Ra,
			&i.Dec,
			&i.Pixscale,
			&i.Radius,
			&i.WidthArcsec,
			&i.HeightArcsec,
			&i.Fieldw,
			&i.Fieldh,
			&i.Orientation,
			&i.Solved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByDateFilterType = `-- name: ListImagesByDateFilterType :many
SELECT id, archive, messier, ngc, ic, rcw, sh2, henize, gum, lbn, common_name, name, filename, thumbnail, type, camera, scope, mount, guiding, exposure, location, date, notes, blink, corrector, ra, dec, pixscale, radius, width_arcsec, height_arcsec, fieldw, fieldh, orientation, solved FROM images
WHERE archive <> 'Y' AND type = ?
ORDER BY date DESC, id
LIMIT ? OFFSET ?
`

type ListImagesByDateFilterTypeParams struct {
	Type   string `json:"type"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListImagesByDateFilterType(ctx context.Context, arg ListImagesByDateFilterTypeParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByDateFilterType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Archive,
			&i.Messier,
			&i.Ngc,
			&i.Ic,
			&i.Rcw,
			&i.Sh2,
			&i.Henize,
			&i.Gum,
			&i.Lbn,
			&i.CommonName,
			&i.Name,
			&i.Filename,
			&i.Thumbnail,
			&i.Type,
			&i.Camera,
			&i.Scope,
			&i.Mount,
			&i.Guiding,
			&i.Exposure,
			&i.Location,
			&i.Date,
			&i.Notes,
			&i.Blink,
			&i.Corrector,
			&i.Ra,
			&i.Dec,
			&i.Pixscale,
			&i.Radius,
			&i.WidthArcsec,
			&i.HeightArcsec,
			&i.Fieldw,
			&i.Fieldh,
			&i.Orientation,
			&i.Solved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByID = `-- name: ListImagesByID :many
SELECT id, archive, messier, ngc, ic, rcw, sh2, henize, gum, lbn, common_name, name, filename, thumbnail, type, camera, scope, mount, guiding, exposure, location, date, notes, blink, corrector, ra, dec, pixscale, radius, width_arcsec, height_arcsec, fieldw, fieldh, orientation, solved FROM images
WHERE archive <> 'Y'
ORDER BY id
LIMIT ? OFFSET ?
`

type ListImagesByIDParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

// Gallery queries: sort by ID (default)
func (q *Queries) ListImagesByID(ctx context.Context, arg ListImagesByIDParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Archive,
			&i.Messier,
			&i.Ngc,
			&i.Ic,
			&i.Rcw,
			&i.Sh2,
			&i.Henize,
			&i.Gum,
			&i.Lbn,
			&i.CommonName,
			&i.Name,
			&i.Filename,
			&i.Thumbnail,
			&i.Type,
			&i.Camera,
			&i.Scope,
			&i.Mount,
			&i.Guiding,
			&i.Exposure,
			&i.Location,
			&i.Date,
			&i.Notes,
			&i.Blink,
			&i.Corrector,
			&i.Ra,
			&i.Dec,
			&i.Pixscale,
			&i.Radius,
			&i.WidthArcsec,
			&i.HeightArcsec,
			&i.Fieldw,
			&i.Fieldh,
			&i.Orientation,
			&i.Solved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByIDFilterCamera = `-- name: ListImagesByIDFilterCamera :many
SELECT id, archive, messier, ngc, ic, rcw, sh2, henize, gum, lbn, common_name, name, filename, thumbnail, type, camera, scope, mount, guiding, exposure, location, date, notes, blink, corrector, ra, dec, pixscale, radius, width_arcsec, height_arcsec, fieldw, fieldh, orientation, solved FROM images
WHERE archive <> 'Y' AND camera = ?
ORDER BY id
LIMIT ? OFFSET ?
`

type ListImagesByIDFilterCameraParams struct {
	Camera string `json:"camera"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

// Filtered by camera
func (q *Queries) ListImagesByIDFilterCamera(ctx context.Context, arg ListImagesByIDFilterCameraParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByIDFilterCamera, arg.Camera, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Archive,
			&i.Messier,
			&i.Ngc,
			&i.Ic,
			&i.Rcw,
			&i.Sh2,
			&i.Henize,
			&i.Gum,
			&i.Lbn,
			&i.CommonName,
			&i.Name,
			&i.Filename,
			&i.Thumbnail,
			&i.Type,
			&i.Camera,
			&i.Scope,
			&i.Mount,
			&i.Guiding,
			&i.Exposure,
			&i.Location,
			&i.Date,
			&i.Notes,
			&i.Blink,
			&i.Corrector,
			&i.Ra,
			&i.Dec,
			&i.Pixscale,
			&i.Radius,
			&i.WidthArcsec,
			&i.HeightArcsec,
			&i.Fieldw,
			&i.Fieldh,
			&i.Orientation,
			&i.Solved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByIDFilterScope = `-- name: ListImagesByIDFilterScope :many
SELECT id, archive, messier, ngc, ic, rcw, sh2, henize, gum, lbn, common_name, name, filename, thumbnail, type, camera, scope, mount, guiding, exposure, location, date, notes, blink, corrector, ra, dec, pixscale, radius, width_arcsec, height_arcsec, fieldw, fieldh, orientation, solved FROM images
WHERE archive <> 'Y' AND scope = ?
ORDER BY id
LIMIT ? OFFSET ?
`

type ListImagesByIDFilterScopeParams struct {
	Scope  string `json:"scope"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

// Filtered by scope
func (q *Queries) ListImagesByIDFilterScope(ctx context.Context, arg ListImagesByIDFilterScopeParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByIDFilterScope, arg.Scope, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Archive,
			&i.Messier,
			&i.Ngc,
			&i.Ic,
			&i.Rcw,
			&i.Sh2,
			&i.Henize,
			&i.Gum,
			&i.Lbn,
			&i.CommonName,
			&i.Name,
			&i.Filename,
			&i.Thumbnail,
			&i.Type,
			&i.Camera,
			&i.Scope,
			&i.Mount,
			&i.Guiding,
			&i.Exposure,
			&i.Location,
			&i.Date,
			&i.Notes,
			&i.Blink,
			&i.Corrector,
			&i.Ra,
			&i.Dec,
			&i.Pixscale,
			&i.Radius,
			&i.WidthArcsec,
			&i.HeightArcsec,
			&i.Fieldw,
			&i.Fieldh,
			&i.Orientation,
			&i.Solved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByIDFilterType = `-- name: ListImagesByIDFilterType :many
SELECT id, archive, messier, ngc, ic, rcw, sh2, henize, gum, lbn, common_name, name, filename, thumbnail, type, camera, scope, mount, guiding, exposure, location, date, notes, blink, corrector, ra, dec, pixscale, radius, width_arcsec, height_arcsec, fieldw, fieldh, orientation, solved FROM images
WHERE archive <> 'Y' AND type = ?
ORDER BY id
LIMIT ? OFFSET ?
`

type ListImagesByIDFilterTypeParams struct {
	Type   string `json:"type"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

// Filtered by object type
func (q *Queries) ListImagesByIDFilterType(ctx context.Context, arg ListImagesByIDFilterTypeParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByIDFilterType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Archive,
			&i.Messier,
			&i.Ngc,
			&i.Ic,
			&i.Rcw,
			&i.Sh2,
			&i.Henize,
			&i.Gum,
			&i.Lbn,
			&i.CommonName,
			&i.Name,
			&i.Filename,
			&i.Thumbnail,
			&i.Type,
			&i.Camera,
			&i.Scope,
			&i.Mount,
			&i.Guiding,
			&i.Exposure,
			&i.Location,
			&i.Date,
			&i.Notes,
			&i.Blink,
			&i.Corrector,
			&i.Ra,
			&i.Dec,
			&i.Pixscale,
			&i.Radius,
			&i.WidthArcsec,
			&i.HeightArcsec,
			&i.Fieldw,
			&i.Fieldh,
			&i.Orientation,
			&i.Solved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByType = `-- name: ListImagesByType :many
SELECT id, archive, messier, ngc, ic, rcw, sh2, henize, gum, lbn, common_name, name, filename, thumbnail, type, camera, scope, mount, guiding, exposure, location, date, notes, blink, corrector, ra, dec, pixscale, radius, width_arcsec, height_arcsec, fieldw, fieldh, orientation, solved FROM images
WHERE archive <> 'Y'
ORDER BY type, id
LIMIT ? OFFSET ?
`

type ListImagesByTypeParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListImagesByType(ctx context.Context, arg ListImagesByTypeParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Archive,
			&i.Messier,
			&i.Ngc,
			&i.Ic,
			&i.Rcw,
			&i.Sh2,
			&i.Henize,
			&i.Gum,
			&i.Lbn,
			&i.CommonName,
			&i.Name,
			&i.Filename,
			&i.Thumbnail,
			&i.Type,
			&i.Camera,
			&i.Scope,
			&i.Mount,
			&i.Guiding,
			&i.Exposure,
			&i.Location,
			&i.Date,
			&i.Notes,
			&i.Blink,
			&i.Corrector,
			&i.Ra,
			&i.Dec,
			&i.Pixscale,
			&i.Radius,
			&i.WidthArcsec,
			&i.HeightArcsec,
			&i.Fieldw,
			&i.Fieldh,
			&i.Orientation,
			&i.Solved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByTypeFilterType = `-- name: ListImagesByTypeFilterType :many
SELECT id, archive, messier, ngc, ic, rcw, sh2, henize, gum, lbn, common_name, name, filename, thumbnail, type, camera, scope, mount, guiding, exposure, location, date, notes, blink, corrector, ra, dec, pixscale, radius, width_arcsec, height_arcsec, fieldw, fieldh, orientation, solved FROM images
WHERE archive <> 'Y' AND type = ?
ORDER BY type, id
LIMIT ? OFFSET ?
`

type ListImagesByTypeFilterTypeParams struct {
	Type   string `json:"type"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListImagesByTypeFilterType(ctx context.Context, arg ListImagesByTypeFilterTypeParams) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, listImagesByTypeFilterType, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Archive,
			&i.Messier,
			&i.Ngc,
			&i.Ic,
			&i.Rcw,
			&i.Sh2,
			&i.Henize,
			&i.Gum,
			&i.Lbn,
			&i.CommonName,
			&i.Name,
			&i.Filename,
			&i.Thumbnail,
			&i.Type,
			&i.Camera,
			&i.Scope,
			&i.Mount,
			&i.Guiding,
			&i.Exposure,
			&i.Location,
			&i.Date,
			&i.Notes,
			&i.Blink,
			&i.Corrector,
			&i.Ra,
			&i.Dec,
			&i.Pixscale,
			&i.Radius,
			&i.WidthArcsec,
			&i.HeightArcsec,
			&i.Fieldw,
			&i.Fieldh,
			&i.Orientation,
			&i.Solved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservations = `-- name: ListObservations :many
SELECT id, name, thumbnail, ra, dec, fieldw, fieldh, orientation
FROM images
WHERE ra IS NOT NULL AND dec IS NOT NULL
`

type ListObservationsRow struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Thumbnail   string          `json:"thumbnail"`
	Ra          sql.NullFloat64 `json:"ra"`
	Dec         sql.NullFloat64 `json:"dec"`
	Fieldw      sql.NullFloat64 `json:"fieldw"`
	Fieldh      sql.NullFloat64 `json:"fieldh"`
	Orientation sql.NullFloat64 `json:"orientation"`
}

// Skymap observations (images with plate-solve data)
func (q *Queries) ListObservations(ctx context.Context) ([]ListObservationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listObservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListObservationsRow{}
	for rows.Next() {
		var i ListObservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Thumbnail,
			&i.Ra,
			&i.Dec,
			&i.Fieldw,
			&i.Fieldh,
			&i.Orientation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImage = `-- name: UpdateImage :exec
UPDATE images SET
    archive = ?, messier = ?, ngc = ?, ic = ?, rcw = ?, sh2 = ?,
    henize = ?, gum = ?, lbn = ?, common_name = ?,
    name = ?, filename = ?, thumbnail = ?, type = ?, camera = ?,
    scope = ?, mount = ?, guiding = ?, exposure = ?, location = ?,
    date = ?, notes = ?, blink = ?, corrector = ?,
    ra = ?, dec = ?, pixscale = ?, radius = ?,
    width_arcsec = ?, height_arcsec = ?,
    fieldw = ?, fieldh = ?, orientation = ?, solved = ?
WHERE id = ?
`

type UpdateImageParams struct {
	Archive      string          `json:"archive"`
	Messier      string          `json:"messier"`
	Ngc          string          `json:"ngc"`
	Ic           string          `json:"ic"`
	Rcw          string          `json:"rcw"`
	Sh2          string          `json:"sh2"`
	Henize       string          `json:"henize"`
	Gum          string          `json:"gum"`
	Lbn          string          `json:"lbn"`
	CommonName   string          `json:"common_name"`
	Name         string          `json:"name"`
	Filename     string          `json:"filename"`
	Thumbnail    string          `json:"thumbnail"`
	Type         string          `json:"type"`
	Camera       string          `json:"camera"`
	Scope        string          `json:"scope"`
	Mount        string          `json:"mount"`
	Guiding      string          `json:"guiding"`
	Exposure     string          `json:"exposure"`
	Location     string          `json:"location"`
	Date         string          `json:"date"`
	Notes        string          `json:"notes"`
	Blink        string          `json:"blink"`
	Corrector    string          `json:"corrector"`
	Ra           sql.NullFloat64 `json:"ra"`
	Dec          sql.NullFloat64 `json:"dec"`
	Pixscale     sql.NullFloat64 `json:"pixscale"`
	Radius       sql.NullFloat64 `json:"radius"`
	WidthArcsec  sql.NullFloat64 `json:"width_arcsec"`
	HeightArcsec sql.NullFloat64 `json:"height_arcsec"`
	Fieldw       sql.NullFloat64 `json:"fieldw"`
	Fieldh       sql.NullFloat64 `json:"fieldh"`
	Orientation  sql.NullFloat64 `json:"orientation"`
	Solved       string          `json:"solved"`
	ID           string          `json:"id"`
}

// Admin: update image
func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) error {
	_, err := q.db.ExecContext(ctx, updateImage,
		arg.Archive,
		arg.Messier,
		arg.Ngc,
		arg.Ic,
		arg.Rcw,
		arg.Sh2,
		arg.Henize,
		arg.Gum,
		arg.Lbn,
		arg.CommonName,
		arg.Name,
		arg.Filename,
		arg.Thumbnail,
		arg.Type,
		arg.Camera,
		arg.Scope,
		arg.Mount,
		arg.Guiding,
		arg.Exposure,
		arg.Location,
		arg.Date,
		arg.Notes,
		arg.Blink,
		arg.Corrector,
		arg.Ra,
		arg.Dec,
		arg.Pixscale,
		arg.Radius,
		arg.WidthArcsec,
		arg.HeightArcsec,
		arg.Fieldw,
		arg.Fieldh,
		arg.Orientation,
		arg.Solved,
		arg.ID,
	)
	return err
}

const updateImagePlateSolve = `-- name: UpdateImagePlateSolve :exec
UPDATE images SET
    ra = ?, dec = ?, pixscale = ?, radius = ?,
    width_arcsec = ?, height_arcsec = ?,
    fieldw = ?, fieldh = ?, orientation = ?, solved = ?
WHERE id = ?
`

type UpdateImagePlateSolveParams struct {
	Ra           sql.NullFloat64 `json:"ra"`
	Dec          sql.NullFloat64 `json:"dec"`
	Pixscale     sql.NullFloat64 `json:"pixscale"`
	Radius       sql.NullFloat64 `json:"radius"`
	WidthArcsec  sql.NullFloat64 `json:"width_arcsec"`
	HeightArcsec sql.NullFloat64 `json:"height_arcsec"`
	Fieldw       sql.NullFloat64 `json:"fieldw"`
	Fieldh       sql.NullFloat64 `json:"fieldh"`
	Orientation  sql.NullFloat64 `json:"orientation"`
	Solved       string          `json:"solved"`
	ID           string          `json:"id"`
}

// Admin: update plate-solve results
func (q *Queries) UpdateImagePlateSolve(ctx context.Context, arg UpdateImagePlateSolveParams) error {
	_, err := q.db.ExecContext(ctx, updateImagePlateSolve,
		arg.Ra,
		arg.Dec,
		arg.Pixscale,
		arg.Radius,
		arg.WidthArcsec,
		arg.HeightArcsec,
		arg.Fieldw,
		arg.Fieldh,
		arg.Orientation,
		arg.Solved,
		arg.ID,
	)
	return err
}
